version: '2'
services:
 mysql:
  image: mysql:latest
  container_name: kamailio_mysql
  ports:
   - "3306:3306"
  env_file:
   - .env
 kamailio:
  build: ./kamailio-setup
  image: linuxmaniac/pkg-kamailio-docker:jessie-modified
  container_name: kamailio
  ports: 
   - "127.0.0.1:5060:5060/udp"
  env_file:
   - .env
  volumes:
   - ./kamailio:/code:rw
  depends_on:
   - mysql
  entrypoint: tail -f /dev/null
 nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - /etc/letsencrypt/certs:/etc/nginx/certs:ro
   - /etc/nginx/vhost.d
   - /usr/share/nginx/html
   - /var/run/docker.sock:/tmp/docker.sock:ro
  labels:
   - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
 nginx-proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: nginx-proxy-companion
  volumes:
   - /etc/letsencrypt/certs:/etc/nginx/certs:rw
   - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
   - nginx-proxy
 apache2:
  build: ./webserver
  image: webserver:v1.0
  container_name: apache2_webserver
  ports:
   - "80"
   - "443"
  environment:
   - VIRTUAL_HOST=${DOMAIN}
