version: '3'
services:
 mysql:
  image: mysql:latest
  container_name: kamailio_mysql
  ports:
   - "3306:3306"
 kamailio:
  image: linuxmaniac/pkg-kamailio-docker:jessie
  container_name: kamailio
  ports: 
   - "127.0.0.1:5060:5060/udp"
  depends_on:
   - mysql
  entrypoint: tail -f /dev/null
 apache2:
  build: ./webserver
  image: webserver:v1.0
  container_name: apache2_webserver
  ports:
   - "80"
   - "443"
  volumes:
   - /etc/letsencrypt:/etc/letsencrypt
   - /var/lib/letsencrypt:/var/lib/letsencrypt
  depends_on:
   - certbot
 certbot:
  image: certbot/certbot
  container_name: certbot
  ports:
   - "80"
   - "443"
  volumes:
   - /etc/letsencrypt:/etc/letsencrypt
   - /var/lib/letsencrypt:/var/lib/letsencrypt
  entrypoint: ""
  command: certbot auth -n --standalone -d ${DOMAIN} --agree-tos --email ${DOMAIN_EMAIL}
